### ISSUE TITLE
Plugin fails on Craft CMS 3.0.0-beta.21

### ISSUE THREAD

**Issue by acehead** [nystudio107/craft3-fastcgicachebust#1]
After updating to Craft CMS 3.0.0-beta.21 following error message is shown:
`Unable to locate message source for category 'fastcgicachebust'.`

I believe it is caused by the following recent change in Craft:
`Plugin handles are kebab-cased now rather than camelCased. Plugins’ Craft::t() and |t() calls, translation files, and template paths must be updated accordingly, as well as any plugin config files in Craft 3 projects.`
https://github.com/craftcms/cms/blob/develop/CHANGELOG-v3.md

**Comment by khalwat** [comment]
Fixed in 1.0.1
