### ISSUE TITLE
UnexpectedValueException

### ISSUE THREAD

**Issue by RyanRoberts** [nystudio107/craft3-fastcgicachebust#14]
### Describe the bug

First, apologies if this is actually nothing to do with your plugin, but it only happens when FastCGI Cache Bust is installed.

I get the following error when submitting a form (I'm using [ExpressForms](https://craft.express/forms/v1/)):

```
UnexpectedValueException
FilesystemIterator::__construct(/etc/nginx/cache/website.name/9): failed to open dir: Permission denied
```

I can provide the full stack trace but I'd rather do that privately as it references the client's site.

### To reproduce
Steps to reproduce the behaviour:
1. Install both FastCGI Cache Bust and Express Forms.
2. Create a form that submits data to Craft and sends it via email.
3. Send the form…
3. See above for the error.

### Expected behaviour
Not to get the error. It actually does save in the form submission in Craft but I don't think emails are sending, I'm not sure if that's relevant. 

### Versions
Express Forms: 1.0.8
FastCGI Cache Bust: 1.0.9
Craft CMS: 3.5.17.1

**Comment by RyanRoberts** [comment]
Is this likely to be looked at? No bother if not. Thanks.

**Comment by khalwat** [comment]
Very likely the path `/etc/nginx/cache/website.name/9` was entered into the plugin as the path to the Fast CGI  Cache dir, but that directory doesn't exist.

You'll see the error message every time it attempts to clear the cache (whenever you save an Element).

**Comment by RyanRoberts** [comment]
@khalwat Sorry, "website.name" is what I renamed it to hide the client's domain. The path is correct and the cache exists. 

But on looking at this again I'm thinking it may have more to do with the permission denied.

**Comment by khalwat** [comment]
yep, that was the next thing I was going to say -- the permissions need to be such that whatever user/group the PHP process runs as can have read/write permission
