### ISSUE TITLE
Flush cache if SEOmatic settings are saved

### ISSUE THREAD

**Issue by wbrowar** [nystudio107/craft3-fastcgicachebust#2]
Since SEOmatic affects the front-end, it would be good to automatically flush the FastCGI cache when SEOmatic's settings are changed. This could be an option, but I can't see when you wouldn't want this to happen when SEOmatic is updated.

**Comment by khalwat** [comment]
Yeah I need to add a generic event that can be triggered.

**Comment by khalwat** [comment]
This was implemented in SEOmatic 3.0.0-beta.23
