### ISSUE TITLE
FR: don't bust cache during Preview editing

### ISSUE THREAD

**Issue by thisisjamessmith** [nystudio107/craft3-fastcgicachebust#37]
### Is your feature request related to a problem? Please describe.

The cache is busted whenever the Preview frame reloads, which is basically on keyup. This seems rather wasteful.

### Describe the solution you would like
Don't clear the cache until the final Save event.

### Describe alternatives you have considered
I'm not sure if this might be possible by wrangling the fastcgi config file, but would be good to have it baked in by default.

**Comment by khalwat** [comment]
Do you have ideas about how this might be accomplished? One thing I can think of is if these are saved as drafts, we could ignore the saving of any element that is a draft?

**Comment by khalwat** [comment]
Also can you tell me whether you're using Craft 3 or Craft 4?

**Comment by khalwat** [comment]
Looks like `isDraftOrRevision()` was added in Craft 3.2: https://github.com/craftcms/cms/blob/v3/CHANGELOG.md#320---2019-07-09

So if I made these changes, I'd likely bump the requirements up to that, to keep things sane.

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-fastcgicachebust/commit/efd613cd0b07e3426894a5afcb7280fdbea4818f & https://github.com/nystudio107/craft-fastcgicachebust/commit/1bd424acbfe9c539ebd56ca32bf86ba8eded622d

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-fastcgicachebust": "dev-develop as 1.0.11”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-fastcgicachebust": "dev-develop-v4 as 4.0.0”,
```
Then do a `composer clear-cache && composer update`

**Comment by thisisjamessmith** [comment]
Hi Andrew,

Many thanks for doing this during the holiday season, and sorry for the delay getting back to you! Will get this tested soon.

**Comment by khalwat** [comment]
yep, lmk if it works for you

**Comment by thisisjamessmith** [comment]
Seems to be working perfectly (Craft 4 tested), thanks Andrew!

**Comment by khalwat** [comment]
Great, thanks! I will cut a release.

**Comment by khalwat** [comment]
Released as:

Craft 3: Version 1.0.11 -> https://github.com/nystudio107/craft-fastcgicachebust/releases/tag/1.0.11

Craft 4: Version 4.0.0 -> https://github.com/nystudio107/craft-fastcgicachebust/releases/tag/4.0.0
