### ISSUE TITLE
Support environment variables / aliases in plugin settings?

### ISSUE THREAD

**Issue by proimage** [nystudio107/craft3-fastcgicachebust#9]
Seems like the plugin doesn't allow using an environment var or alias to determine the path to the FastCGI cache. Is that a correct conclusion, and can that be added?

**Comment by andrewmenich** [comment]
~~If @khalwat is open to a PR I'd be happy to get this implemented!~~

I didn't realize the solution to this is as simple as adding a `fastcgi-cache-bust.php` file to your `config` folder. See here for details [https://github.com/nystudio107/craft-fastcgicachebust/blob/v1/src/config.php](https://github.com/nystudio107/craft-fastcgicachebust/blob/v1/src/config.php)

**Comment by khalwat** [comment]
Added support for aliases & environment variables in: https://github.com/nystudio107/craft-fastcgicachebust/commit/63b48c7a297cadf01f2214b546183bc956d396e9
